# Définit l'installation des packages suivants des variables (common_packages). La liste des packages à installer se situe dans "../defaults/main.yml"
- name: Install common packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}" # ceci permet de boucler sur la liste common_packages
