#- name: Create common users
#  become: true
#  ansible.builtin.user:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ users }}" # ceci permet de boucler sur la liste common_users0

- name: Create common users
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: yes
    home: "{{ item.homedir }}"
    shell: /bin/bash
    groups: "{{ item.group }},sudo"
  with_items: "{{ users }}"
