# Utilisé pour des tests
#- name: Create common users
#  become: true
#  ansible.builtin.user:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ users }}" # ceci permet de boucler sur la liste common_users0

# Définit les utilisateurs à créer en utilisant des variables. La liste des utilisateurs à installer se situe dans le chemin relatif "TP01/Ansible/inventories/vagrant_lab/group_vars/ynov.yml"
- name: Create common users
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    createhome: yes
    home: "{{ item.homedir }}"
    shell: /bin/bash
    groups: "{{ item.group }},sudo"
  with_items: "{{ users }}"
