- name: Create webroot
  become: true
  file:
    path: "{{ nginx_webroot }}"
    state: directory

- name: Create index
  become: true
  copy:
    dest: "{{ nginx_webroot }}/index.html"
    content: "{{ nginx_index_content }}"

- name: NGINX Virtual Host
  become: true
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ nginx_servername }}.conf
