---
- name: Install web server
  dnf:
    name: apache2
    state: present

- name: Copy web application files
  copy:
    src: files/index.html
    dest: /var/www/html/

- name: Start web server
  service:
    name: apache2
    state: started
